### ISSUE TITLE
Error running"node taker.js"

### ISSUE THREAD

**Issue by pathaksa** [etherdelta/bots#21]
Getting this error when running "node taker.js". I have added the address and private  key on line 9 and 10.

  const [walletETH, walletToken, EtherDeltaETH, EtherDeltaToken] = results;
        ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by pathaksa** [comment]
Fixed it by running nvm install node
